import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { Inter as FontSans } from "next/font/google"
import { TRPCReactProvider } from "~/trpc/react";
import Image from 'next/image';

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Verse Assignment - jcoyne",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <div className="flex flex-row bg-neutral-100 h-14 center justify-between items-center px-7">
      <a href={"/"}>
        <Image
          // className="m-20"
            src="/title.svg"
            alt="Verse Logo"
            width={75}
            height={20}
        />
      </a>
          <SignedOut>          
            <SignInButton mode="modal"/>        
          </SignedOut>        
          <SignedIn>          
            <UserButton afterSignOutUrl="/" afterMultiSessionSingleSignOutUrl="/" />        
          </SignedIn>    
    </div>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${fontSans.variable}`}>
      <body>
        <ClerkProvider>  
          <TopNav/>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
